# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_img', models.CharField(max_length=100)),
                ('good_detail', models.CharField(max_length=100)),
                ('good_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trackid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mml_goods',
            },
        ),
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_img', models.ImageField(upload_to='lunboimg/')),
                ('db_img_detail', models.CharField(max_length=100)),
                ('db_img_firsttime', models.DateTimeField(auto_now_add=True)),
                ('db_img_lasttime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mml_lunbos',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_uname', models.CharField(max_length=40, unique=True)),
                ('db_headimg', models.CharField(default='/static/userheadimg/hehe.jpg', max_length=150)),
                ('db_utel', models.CharField(max_length=20, unique=True)),
                ('db_upassword', models.CharField(max_length=256)),
                ('db_token', models.CharField(default='', max_length=256)),
                ('db_uFirstTime', models.DateTimeField(auto_now=True)),
                ('db_uLastTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mml_userinfos',
            },
        ),
    ]
