# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='db_img',
            field=models.ImageField(upload_to='uploadfiles/lunboimg/'),
        ),
    ]
