# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0002_auto_20181211_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='db_uname',
            field=models.CharField(default='用户14165507', max_length=40, unique=True),
        ),
    ]
