# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0003_auto_20181211_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='db_uname',
        ),
    ]
