# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0004_remove_userinfo_db_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='db_headimg',
            field=models.CharField(default='person.png', max_length=150),
        ),
    ]
