# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0005_auto_20181211_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mmloo_carts',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20)),
                ('mmlprice', models.CharField(max_length=20)),
                ('headimg', models.CharField(max_length=255)),
                ('picnum', models.CharField(max_length=255)),
                ('picture1', models.CharField(max_length=255)),
                ('picture2', models.CharField(max_length=255)),
                ('picture3', models.CharField(max_length=255)),
                ('picture4', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelTable(
            name='good',
            table='mmloo_goods',
        ),
        migrations.AlterModelTable(
            name='lunbo',
            table='mmloo_lunbos',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='mmloo_userinfos',
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmloo_shop.Good'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmloo_shop.UserInfo'),
        ),
    ]
