# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0006_auto_20181212_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('identifier', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmloo_shop.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.RemoveField(
            model_name='good',
            name='trackid',
        ),
        migrations.AddField(
            model_name='good',
            name='picture1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='good',
            name='picture2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='good',
            name='picture3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='good',
            name='picture4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmloo_shop.Good'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmloo_shop.Order'),
        ),
    ]
