# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0007_auto_20181212_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='picture1',
            field=models.ImageField(max_length=255, upload_to='uploadfiles/detailimg'),
        ),
        migrations.AlterField(
            model_name='good',
            name='picture2',
            field=models.ImageField(max_length=255, upload_to='uploadfiles/detailimg'),
        ),
        migrations.AlterField(
            model_name='good',
            name='picture3',
            field=models.ImageField(max_length=255, upload_to='uploadfiles/detailimg'),
        ),
        migrations.AlterField(
            model_name='good',
            name='picture4',
            field=models.ImageField(max_length=255, upload_to='uploadfiles/detailimg'),
        ),
    ]
