# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0008_auto_20181212_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_img',
            field=models.ImageField(max_length=255, upload_to='uploadfiles/detailimg'),
        ),
    ]
