# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0009_auto_20181212_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='goodid',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
