# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0010_good_goodid'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='good_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='good',
            name='good_explain',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='good',
            name='good_farther',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='good',
            name='good_ffarther',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='good',
            name='good_fffarther',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='good',
            name='good_freight',
            field=models.IntegerField(default=0),
        ),
    ]
