# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0011_auto_20181213_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_freight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
