# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmloo_shop', '0012_auto_20181213_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='goodid',
            field=models.IntegerField(default=1),
        ),
    ]
